{
    'name': 'sid_projects_dossier',
    'version': '1.0.2',
    'category': 'Sales',
    'license': 'AGPL-3',
    'summary': 'Control de Base Imponible',
    'description': 'Módulo de gestión de Dossieres de Calidad',
    'author': 'oscarsidsa81',
    'depends': ['base','crm','sale_management','documents','oct_sale_extra_fields'],
    'data': [
        'security/ir.model.access.csv',
        'views/sid_projects_dossier_sales.xml',
        'data/sid_dossier_assign_wizard.xml',
        'data/document_actions.xml',
        'data/document_folders.xml',
        'data/document_group.xml',
        'data/documents_tags.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}